// OAUTH2
export const OAUTH2_CONFIGURE = 'OAUTH2/CONFIGURE';
export const OAUTH2_SET_TOKEN = 'OAUTH2/SET_TOKEN';
export const OAUTH2_SET_AUTHENTICATED = 'OAUTH2/SET_AUTHENTICATED';
export const OAUTH2_GET_TOKEN = 'OAUTH2/GET_TOKEN';
export const OAUTH2_REFRESH_TOKEN = 'OAUTH2/REFRESH_TOKEN';

// PREFERENCES
export const PREFERENCES_SET_KEY = 'PREFERENCES/SET_KEY';

// NINETOFIVER
//Mutations
export const NINETOFIVER_SET_CONTRACT_ROLES = 'NINETOFIVER/SET_CONTRACT_ROLES';
export const NINETOFIVER_SET_CONTRACT_USERS = 'NINETOFIVER/SET_CONTRACT_USERS';
export const NINETOFIVER_SET_CONTRACTS = 'NINETOFIVER/SET_CONTRACTS';
export const NINETOFIVER_SET_LEAVE_TYPES = 'NINETOFIVER/SET_LEAVE_TYPES';
export const NINETOFIVER_SET_TIMESHEETS = 'NINETOFIVER/SET_TIMESHEETS';
export const NINETOFIVER_SET_USER = 'NINETOFIVER/SET_USER';
export const NINETOFIVER_SET_USERS = 'NINETOFIVER/SET_USERS';
export const NINETOFIVER_SET_LOCATIONS = 'NINETOFIVER/SET_LOCATIONS';
export const NINETOFIVER_SET_PERFORMANCE_TYPES = 'NINETOFIVER/SET_PERFORMANCE_TYPES';

//Actions
export const NINETOFIVER_API_REQUEST = 'NINETOFIVER/API_REQUEST';
export const NINETOFIVER_RELOAD_CONTRACT_ROLES = 'NINETOFIVER/RELOAD_CONTRACT_ROLES';
export const NINETOFIVER_RELOAD_CONTRACT_USERS = 'NINETOFIVER/RELOAD_CONTRACT_USERS';
export const NINETOFIVER_RELOAD_CONTRACTS = 'NINETOFIVER/RELOAD_CONTRACTS';
export const NINETOFIVER_RELOAD_LEAVE_TYPES = 'NINETOFIVER/RELOAD_LEAVE_TYPES';
export const NINETOFIVER_RELOAD_PERFORMANCE_TYPES = 'NINETOFIVER/RELOAD_PERFORMANCE_TYPES';
export const NINETOFIVER_RELOAD_TIMESHEETS = 'NINETOFIVER/RELOAD_TIMESHEETS';
export const NINETOFIVER_RELOAD_USER = 'NINETOFIVER/RELOAD_USER';
export const NINETOFIVER_RELOAD_USERS = 'NINETOFIVER/RELOAD_USERS';
export const NINETOFIVER_RELOAD_LOCATIONS = 'NINETOFIVER/RELOAD_LOCATIONS'
