export const OAUTH2_CONFIGURE = 'OAUTH2/CONFIGURE'
export const OAUTH2_SET_TOKEN = 'OAUTH2/SET_TOKEN'
export const OAUTH2_GET_TOKEN = 'OAUTH2/GET_TOKEN'
export const OAUTH2_REFRESH_TOKEN = 'OAUTH2/REFRESH_TOKEN'
export const OAUTH2_SET_AUTHENTICATED = 'OAUTH2/SET_AUTHENTICATED'

export const NINETOFIVER_API_REQUEST = 'NINETOFIVER/API_REQUEST'
export const NINETOFIVER_RELOAD_USER = 'NINETOFIVER/RELOAD_USER'
export const NINETOFIVER_SET_USER = 'NINETOFIVER/SET_USER'

export const LEAVE_STATUSES = ['APPROVED', 'REJECTED', 'PENDING', 'DRAFT']